language: php

php:
  - '7.0'
  - '7.1'

cache:
  directories:
    - vendor

install:
  - "composer install --dev"

script:
  - "./vendor/phpunit/phpunit/phpunit -c ./phpunit.xml"
  - "./vendor/bin/test-reporter"
